import { prisma } from '../config/database';
import logger from '../config/logger';
import { startOfDay, endOfDay, subDays } from 'date-fns';

/**
 * Nightly reconciliation service to ensure no gaps in attendance records.
 * Marks absences, holidays, and weekly-offs explicitly in the database.
 */
export async function reconcileAttendance(date: Date = new Date()): Promise<void> {
    try {
        const targetDate = startOfDay(date);
        const dayOfWeek = targetDate.getDay(); // 0 = Sunday

        logger.info(`Starting attendance reconciliation for ${targetDate.toDateString()}`);

        const [activeEmployees, holidays] = await Promise.all([
            prisma.employee.findMany({ where: { isActive: true } }),
            prisma.holiday.findMany({
                where: {
                    date: { gte: startOfDay(targetDate), lte: endOfDay(targetDate) }
                }
            })
        ]);

        const isHoliday = holidays.length > 0;
        const isSunday = dayOfWeek === 0;

        for (const emp of activeEmployees) {
            // Check if record already exists for this date
            const existing = await prisma.attendanceLog.findUnique({
                where: {
                    employeeId_date_tenantId: {
                        employeeId: emp.id,
                        date: targetDate,
                        tenantId: emp.tenantId
                    }
                }
            });

            if (existing) {
                // Determine if 'present' status needs adjustment (e.g. if it was manually set to present but working hours are 0)
                continue;
            }

            // No record exists, determine the "default" status for today
            let status = 'absent';
            let reason = 'No logs found';

            if (isHoliday) {
                status = 'holiday';
                reason = holidays[0].name;
            } else if (isSunday) {
                status = 'weekly_off';
                reason = 'Weekly Off (Sunday)';
            } else {
                // Check if there is an approved leave for this date
                const leave = await prisma.leaveEntry.findFirst({
                    where: {
                        employeeId: emp.id,
                        status: 'approved',
                        startDate: { lte: targetDate },
                        endDate: { gte: targetDate }
                    },
                    include: { leaveType: true }
                });

                if (leave) {
                    status = 'leave_paid';
                    reason = leave.leaveType.name;
                }
            }

            // Create the record
            await prisma.attendanceLog.create({
                data: {
                    tenantId: emp.tenantId,
                    employeeId: emp.id,
                    date: targetDate,
                    status: status,
                    rawData: JSON.stringify({ autoGenerated: true, reason })
                }
            });
        }

        logger.info(`Attendance reconciliation completed for ${activeEmployees.length} employees.`);
    } catch (error) {
        logger.error('Attendance reconciliation failed:', error);
    }
}
